version: '3.8'
services:
  app:
    build: .
    container_name: socket-chat
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    command: sleep infinity
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - socket-chat-net
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    healthcheck:
      test: redis-cli ping
    networks:
      - socket-chat-net

networks:
  socket-chat-net:
    external: true
